name: Docker Image CI

on: push
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      
  
    
      
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
      
    - name: Build and push tagged Docker image
      run: |
       export GIT_COMMIT=$(git log -1 --format=%h)
       run: | 
       docker build . --file Dockerfile --tag pkatwal/demo:$GIT_COMMIT
       run: |
       docker push pkatwal/demo:$GIT_COMMIT
